# Generated by Django 4.0.6 on 2022-07-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_firstname_contact_subject_remove_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='matiere',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='taille',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
