# Generated by Django 4.0.6 on 2022-07-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Prix',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='Titre',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='product',
            name='Stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
