# Generated by Django 4.0.6 on 2022-07-26 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_price_product_prix_rename_title_product_titre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Prix',
            new_name='prix',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Stock',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Titre',
            new_name='titre',
        ),
    ]
